
project_id = "dulmmxtkgqkcfovvfxzu"

[functions.cash-flow-forecast]
verify_jwt = true

[functions.set-api-key]
verify_jwt = true

[functions.send-invitation]
verify_jwt = true

[functions.create-invited-user]
verify_jwt = false

[functions.get-api-key]
verify_jwt = true

[functions.sat-automation]
verify_jwt = true

[functions.sat-captcha]
verify_jwt = true
